6-learn-react-native
InspiranzaDEV/pruebas pull request #22
Opened 2024-08-04 17:28 UTC by IsaDScmd

2024-08-05 18:17 UTC, rucev requested changes

2024-08-05 18:17 UTC, rucev commented on proof-of-concept/src/components/NotificationButton.jsx
> -import { View, Button } from 'react-native';
Te has cargado un poquito el hook de las notificaciones. Habría que dejar algo tipo:

```js
import { View, Button } from 'react-native';
import MyButton from './MyButton';
import useNotification from '../hooks/useNotification';

export default function NotificationButton() {
    const { scheduleNotification } = useNotification();

    const handlePress = () => {
        scheduleNotification('titulo', 'mensaje notificación', 5) //5 son los segundos que tarda en mostrarlo
    }

    return (
        <MyButton 
            title="Enviar Notificación"
            onPress={handlePress}
         />
    );
}
```

2024-08-12 17:04 UTC, IsaDScmd commented on proof-of-concept/src/components/NotificationButton.jsx
> -import { View, Button } from 'react-native';
Tienes razón, arreglado! >.<

2024-08-14 09:28 UTC, rucev approved these changes
👍

2024-08-14 09:30 UTC, merged